server:
  port: 8877
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application: 
    name: 'mall-manager-ms'
  datasource:
    username: root
    password: root
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai'
pagehelper:
  helper-dialect: mysql
  reasonable: true

 